# Generated by Django 3.1.7 on 2021-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='track_image',
            field=models.CharField(default='hi', max_length=2083),
            preserve_default=False,
        ),
    ]
