# Generated by Django 3.1.7 on 2021-05-15 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
